---
- name: '001 | AUDIT | There should be no /etc/hosts.equiv file on the system'
  stat:
    path: /etc/hosts.equiv
  always_run: yes
  tags:
    - audit

- name: '001 | PATCH | There should be no /etc/hosts.equiv file on the system'
  file:
    path: /etc/hosts.equiv
    state: absent
  tags:
    - patch
