---
- name: '005 | AUDIT | telnetd should not be running'
  command: true
  when: inetd_services.stdout.find('telnet') != -1
  changed_when: false
  always_run: true
  tags:
    - audit

- name: '005 | PATCH | telnetd should not be running'
  replace:
    dest: /etc/inetd.conf
    regexp: '^(telnet.*)$'
    replace: '#\1'
  when:
    - inetd_services.stdout.find('telnet') != -1
  notify: 'Restart inetd'
  tags:
    - patch
